export const profileStats = [
  ['05', 'Locations'], ['40+', 'Team members'], ['30+', 'Clients served'], ['12+', 'Leadership team'], ['06+', 'Service lines']
]
export const serviceOfferings: Record<string, string[]> = {
  ai: ['Chief Digital Office', 'AI Governance Centre', 'Productivity tools', 'ERP implementation support', 'Agentic AI intervention', 'Low-code / no-code solutions'],
  grc: ['Outsourced and co-sourced internal audits', 'Special reviews', 'Enterprise risk management', 'Compliance management', 'Internal financial controls and SOX', 'SOPs and policy frameworks', 'Delegation of authority', 'Business support and organisation matrices'],
  finance: ['Funding', 'Treasury management', 'Due diligence', 'Debt restructuring', 'Investor management', 'Portfolio review'],
  'finance-advisory': ['Managed accounting services', 'Managed payroll services', 'Financial statement preparation', 'Book closure and reporting', 'Secretarial compliances', 'Related-party management'],
  strategy: ['Customer experience', 'Process transformation', 'Cost reduction and improvement', 'Operational excellence', 'Research', 'Margin improvement', 'Revenue and growth', 'Governance and strategy'],
  audit: ['Direct tax advisory', 'Statutory audit', 'Certifications', 'Tax litigation', 'Indirect tax advisory', 'Tax managed services'],
  forensic: ['Pre-investment due diligence', 'Senior management due diligence', 'Corporate investigations', 'Digital forensics', 'Ethics and compliance training', 'Fraud and misconduct investigations', 'IP protection', 'Incident response, data recovery and cyber threat intelligence'],
  'tech-solutions': ['Continuous controls and risk monitoring', 'Decision intelligence', 'AI-native accounts receivable management', 'AI-native finance operations', 'Asset management for malls, offices and construction projects', 'Customised technology solutions']
}
export const leadership = [
  { name: 'Kanhai Choudhary', role: 'Founder & CEO', experience: '17+ years', image: 'kanhai-choudhary.jpeg', bio: "Kanhai Choudhary is a Chartered Accountant with a Big 4 consulting background and the Founder & Managing Director of I-Genext Consulting, a multi service lines boutique tech consulting firm specializing in GRC, Internal audit, Finance advisory, Management consulting and Business Automation for clients across domains and sectors. He also founded Tvat AI Lab, the group's AI-native technology arm, building intelligent platforms for Finance, HR, Audit and Risk Management." },
  { name: 'Manish Mehrotra', role: "Partner & Head \u2013 Retail and Real Estate Operations", experience: '33+ years', image: 'manish-mehrotra.jpeg', bio: "Manish Mehrotra is Partner & Head \u2013 Retail and Real Estate Operations at I-Genext Consulting, bringing over 33 years of leadership experience across retail, real estate, and business operations management. Over his career, he has held senior roles with organizations including DLF, Landmark Dubai, Aditya Birla Group, Tata Teleservices, ITC, Lee Cooper, and Lotto.\n\nAt I-Genext, Manish leads and strengthens the firm's Retail and Real Estate Operations practice, working closely with clients to enhance operational performance, strengthen governance, optimize costs, and improve customer experience \u2014 driving sustainable growth across the sector." },
  { name: 'Vipur Tayal', role: 'Associate Director — Advisory', experience: '13+ years', image: 'vipur-tayal.png', bio: "Vipur Tayal is a Chartered Accountant with over 13 years of experience across ERP implementation, finance and accounts, internal audit, process transformation, and internal controls. He has worked with leading consulting firms including EY, KPMG, and EXL, as well as organizations such as Barclays and DLF, on a wide range of engagements spanning financial advisory, internal audit, and corporate governance." },
  { name: 'Davinder Besoya', role: 'Advisory Board Member', experience: '28+ years', image: 'davinder-besoya.png', bio: "Davinder Besoya brings over 28 years of extensive experience in luxury hospitality and premium retail operations to I-Genext's Advisory Board. He has held senior leadership roles with The Lalit, Hyatt, DLF Retail, and ITC Hotels.\n\nAt I-Genext, Davinder's counsel strengthens the firm's understanding of what drives business success across hospitality and retail \u2014 particularly the role of technology and customer experience in operational excellence." },
]
export const offices = [
  { city: 'Gurugram', label: 'Our base', address: 'WeWork, 6th Floor, DLF Atrium Palace, Udyog Vihar, Gurugram' },
  { city: 'Mumbai', label: 'Maharashtra', address: 'WeWork, Enam Sambhav, BKC, Mumbai' },
  { city: 'Bangalore', label: 'Karnataka', address: 'WeWork Cherry Hills, Embassy Golf Link Business Park, Bangalore' },
  { city: 'Ranchi', label: 'Jharkhand', address: '72, Second Floor, New AG Co-operative Colony, Kadru, Ranchi, Jharkhand' },
  { city: 'Rudrapur', label: 'Uttarakhand', address: 'Nainital Road, Rudrapur, Uttarakhand' }
]
export const platforms = [
  { id: 'plinari', name: 'Plinari', category: 'AI-native finance operations', headline: 'From ERP data to a finance function that moves with your business.', description: 'Connect planning, treasury, closure and reporting on one validated data model. Plinari turns ERP data into working finance intelligence, helping teams reconcile continuously, model decisions and answer business questions with current numbers.', features: ['Dynamic operating plans and budget simulations', 'Treasury, liquidity and accelerated financial closure', 'Continuous reconciliation and FIFO-based gross-margin P&L', 'Automated MIS and chat-based finance collaboration'], color: 'royal', image: 'tvat-plinari.png', graphicLabel: 'ERP data flows through validation into a shared finance model for planning, treasury and closure.' },
  { id: 'edi', name: 'EDI', category: 'Executive Decision Intelligence', headline: 'Move from reviewing yesterday to deciding what comes next.', description: 'Give leadership a shared view of performance with consistent KPIs, drill-downs and scenario modelling. EDI connects business data with conversational, cited answers so leaders can explore a variance, compare options and act with context.', features: ['Consistent KPIs and connected C-suite dashboards', 'What-if simulations with business-unit drill-downs', 'Natural-language questions with cited answers', 'Variance alerts and mobile access for leadership'], color: 'turquoise', image: 'tvat-edi.png', graphicLabel: 'An illustrative scenario comparison shows baseline, growth and pressure paths to support leadership decisions.' },
  { id: 'ccm', name: 'CCM', category: 'Continuous Control Monitoring', headline: 'See control gaps sooner. Put remediation in motion.', description: 'Replace periodic, sample-based reviews with ongoing monitoring across leases, billing, payments, approvals and compliance. Connect exceptions to supporting evidence and accountable owners, helping teams move from detecting issues to preventing recurrence.', features: ['Anomaly detection and process-workflow validation', 'Evidence capture with a traceable audit history', 'Owned remediation workflows and policy obligations', 'Predictive risk views with ERP and property-system integration'], color: 'sky', image: 'tvat-ccm.png', graphicLabel: 'A conceptual controls monitor connects transaction checks, flagged exceptions, evidence and remediation owners.' },
  { id: 'reiq', name: 'REIQ', category: 'Real estate automation', headline: 'One connected operating layer for the real estate lifecycle.', description: 'Bring contracts, sales, project operations, customer relationships, receivables and leasing into a connected AI-enabled ecosystem. REIQ modules can work independently or together, coordinating work across teams and the property lifecycle.', features: ['Contract and lease lifecycle management', 'AI-enabled sales and omnichannel customer journeys', 'Project coordination across teams, vendors and sites', 'ERP-connected receivables and governed collections'], color: 'violet', image: 'tvat-platform-architecture.png', graphicLabel: 'A real estate module map connects contracts, sales, projects, CRM, receivables and leasing through REIQ.' },
  { id: 'vayam', name: 'VayamIQ', category: 'Recruitment orchestration', headline: 'A more structured hiring journey, from role brief to offer.', description: 'Connect recruiters and candidates through one auditable workflow. VayamIQ brings together competency-led job descriptions, AI-assisted shortlisting, assessments, interviews and reusable background verification to support better-informed hiring decisions.', features: ['Competency-mapped job descriptions and CV scoring', 'Psychometric and technical assessments with interview scheduling', 'Reusable, verified background-check records', 'Digital offers, self-service portals and hiring-funnel visibility'], color: 'royal', image: 'tvat-vayam.png', graphicLabel: 'A recruitment funnel progresses from role definition through shortlisting, assessment, verification and offer.' },
  { id: 'convex', name: 'The Convex', category: 'AI Engine Optimization', headline: 'Help your brand get found, cited and represented accurately in AI answers.', description: 'Understand how AI answer engines describe your brand and which sources shape their responses. The Convex connects visibility and competitor tracking with structured knowledge, content improvements and misrepresentation alerts to strengthen your presence in AI-led discovery.', features: ['Multi-engine visibility and prompt-level share of voice', 'Citation attribution and competitor answer mapping', 'Schema, entity and knowledge-graph improvements', 'AI-ready content, misrepresentation alerts and executive reporting'], color: 'turquoise', image: 'tvat-convex.png', graphicLabel: 'Verified brand sources feed structured knowledge and AI answers, with a feedback loop for citation and accuracy monitoring.' }
]