import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import type { PlatformEntry } from '../lib/platform-catalog'
import { HeroVisual } from './CinematicHero'
export default function AdminHero({sessionExpired}:{sessionExpired:()=>void}) {
  const [item,setItem]=useState<PlatformEntry|null>(null),[baseline,setBaseline]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const [files,setFiles]=useState<{photo:File|null;video:File|null}>({photo:null,video:null}),[uploadKey,setUploadKey]=useState(0)
  const dirty=!!item&&JSON.stringify(item)!==baseline
  async function request(url:string,options:RequestInit={}){const r=await fetch(url,options);if(r.status===401){sessionExpired();throw Error('Please sign in again.')}const data=await r.json();if(!r.ok)throw Error(data.message||'The hero could not be saved.');return data}
  function accept(row:PlatformEntry){setItem(row);setBaseline(JSON.stringify(row));setFiles({photo:null,video:null});setUploadKey(x=>x+1)}
  async function load(){setBusy(true);setError('');try{const data=await request('/api/admin/hero-content');if(!data.items[0])throw Error('Hero content is not configured.');accept(data.items[0])}catch(e){setError(e instanceof Error?e.message:'Could not load the hero.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty,busy])
  function edit(key:keyof PlatformEntry,value:string){setItem(row=>row?{...row,[key]:value}:row);setNotice('')}
  async function save(e:FormEvent){e.preventDefault();if(!item)return;setBusy(true);setError('');setNotice('');try{accept((await request('/api/admin/hero-content/hero',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...item,status:'published'})})).item);setNotice('Hero saved and published.')}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
  async function media(kind:'photo'|'video',remove=false){if(!item)return;if(remove&&!confirm('Remove the uploaded '+kind+'?'))return;const file=files[kind];if(!remove&&!file)return;setBusy(true);setError('');setNotice('');try{let result;if(remove)result=await request('/api/admin/hero-content/hero/media/'+kind,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:item.version})});else{const body=new FormData();body.append('file',file!);body.append('version',String(item.version));result=await request('/api/admin/hero-content/hero/'+kind,{method:'POST',body})}accept(result.item);setNotice(remove?'Uploaded '+kind+' removed.':kind==='photo'?'Image uploaded and published. Choose Video or Demo film below if you want motion with this image as the poster.':'Video uploaded and published.')}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
  return <section className="hero-admin"><div className="catalog-admin-heading"><div><h2>Hero banner</h2><p>Manage the opening film, background image and highlighted text.</p></div><button className="admin-secondary" disabled={busy} onClick={()=>{if(!dirty||confirm('Discard unsaved changes?'))void load()}}>Reload</button><a href="/#top" target="_blank" rel="noreferrer">View website &#8599;</a></div>{error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}{!item?<p>Loading hero settings...</p>:<>
    <h3>Background image & video</h3><p className="admin-footnote">The included demo is an animated consulting scene. Upload your own film or image below. Save text changes before uploading media.</p>
    <div className="catalog-upload-grid">{(['photo','video'] as const).map(kind=><div className="catalog-upload" key={kind}><h4>{kind==='photo'?'Background image / video poster':'Background video'}</h4>{kind==='photo'?<img src={item.photo?.previewUrl||'/profile/consulting-hero-poster-v2.png'} alt="Current hero image"/>:<video controls preload="metadata" src={item.video?.previewUrl||'/profile/consulting-hero-demo-v2.webm'} poster={item.photo?.previewUrl||'/profile/consulting-hero-poster-v2.png'} aria-label="Hero video preview"/>}<input key={kind+uploadKey} aria-label={'Choose hero '+kind} type="file" accept={kind==='photo'?'image/png,image/jpeg,image/webp':'video/mp4,video/webm'} disabled={busy||dirty} onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(!file.size||file.size>(kind==='photo'?10:100)*1024*1024){setError('File exceeds the '+(kind==='photo'?10:100)+' MB limit.');return}setFiles(old=>({...old,[kind]:file}));setError('')}}/><p>{kind==='photo'?'PNG, JPG or WebP - up to 10 MB':'MP4 or WebM - up to 100 MB. Use a short landscape video; background audio is muted.'}</p><button className="admin-secondary" disabled={busy||dirty||!files[kind]} onClick={()=>media(kind)}>{item[kind]?'Replace':'Upload'} {kind==='photo'?'image':'video'}</button>{item[kind]&&<button className="admin-secondary" disabled={busy||dirty} onClick={()=>media(kind,true)}>Remove {kind}</button>}</div>)}</div>
    <form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0,marginTop:35}}><legend>Hero text & display</legend><div className="catalog-form-grid">
      {([['name','Eyebrow / introductory line',120],['headline','Main headline',260],['category','Highlighted headline',180],['description','Supporting text',4000],['outcome','Button label',600],['imageAlt','Image description',250]] as const).map(([key,label,max])=><label className={'field '+(key==='description'?'catalog-wide':'')} key={key}>{label}{key==='description'?<textarea value={item[key]} required maxLength={max} rows={3} onChange={e=>edit(key,e.target.value)}/>:<input value={item[key]} required maxLength={max} onChange={e=>edit(key,e.target.value)}/>}</label>)}
      <label className="field">Background type<select value={item.mediaMode} onChange={e=>edit('mediaMode',e.target.value)}><option value="illustration">Included demo film</option><option value="photo">Still image</option><option value="video" disabled={!item.video}>Uploaded video</option></select></label>
    </div><button className="btn btn-primary btn-large" disabled={busy}>{busy?'Saving...':'Save hero'}</button>{dirty&&<p className="admin-footnote">You have unsaved text or display changes.</p>}</fieldset></form><div className="hero-preview"><h3>Live preview</h3><HeroVisual item={item} admin/></div></>}
  </section>
}
