import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { PlatformVisual } from '../lib/platform-catalog'
import type { PlatformEntry } from '../lib/platform-catalog'
const blank = (): PlatformEntry => ({ id:'', anchor:'', group:'productivity', name:'', category:'', headline:'', description:'', features:[], flow:[], outcome:'', color:'royal', order:1, status:'draft', mediaMode:'illustration', imageAlt:'', transcript:'', version:0, illustration:'generic', photo:null, video:null })
export default function AdminPlatforms({ sessionExpired }: { sessionExpired: () => void }) {
  const [items,setItems] = useState<PlatformEntry[]>([])
  const [draft,setDraft] = useState<PlatformEntry | null>(null)
  const [baseline,setBaseline] = useState('')
  const [features,setFeatures] = useState('')
  const [flow,setFlow] = useState('')
  const [filter,setFilter] = useState('all')
  const [loading,setLoading] = useState(true)
  const [busy,setBusy] = useState(false)
  const [error,setError] = useState('')
  const [notice,setNotice] = useState('')
  const [photo,setPhoto] = useState<File | null>(null)
  const [video,setVideo] = useState<File | null>(null)
  const [photoPreview,setPhotoPreview] = useState('')
  const [videoPreview,setVideoPreview] = useState('')
  const [uploadKey,setUploadKey] = useState(0)
  const candidate = draft ? { ...draft, features:features.split('\n').map(x=>x.trim()).filter(Boolean), flow:flow.split('\n').map(x=>x.trim()).filter(Boolean) } : null
  const dirty = candidate !== null && JSON.stringify(candidate) !== baseline
  useEffect(()=>{if(!photo){setPhotoPreview('');return}const url=URL.createObjectURL(photo);setPhotoPreview(url);return()=>URL.revokeObjectURL(url)},[photo])
  useEffect(()=>{if(!video){setVideoPreview('');return}const url=URL.createObjectURL(video);setVideoPreview(url);return()=>URL.revokeObjectURL(url)},[video])
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty||busy){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty,busy])
  async function request(url:string, options:RequestInit={}) { const response=await fetch(url,options);if(response.status===401){sessionExpired();throw Error('Your session ended. Please sign in again.')}const result=await response.json();if(!response.ok)throw Error(result.message||'The change could not be saved.');return result }
  function select(item:PlatformEntry) { setDraft(item);setFeatures(item.features.join('\n'));setFlow(item.flow.join('\n'));setBaseline(JSON.stringify(item));setPhoto(null);setVideo(null);setUploadKey(x=>x+1);setError('');setNotice('') }
  async function load() { setLoading(true);setError('');try{const result=await request('/api/admin/platform-catalog');setItems(result.items);if(result.items.length)select(result.items.find((row:PlatformEntry)=>row.id===draft?.id)||result.items[0]);else{setDraft(null);setBaseline('')}}catch(reason){setError(reason instanceof Error?reason.message:'Could not load sections.')}finally{setLoading(false)} }
  useEffect(()=>{void load()},[])
  function change<K extends keyof PlatformEntry>(key:K,value:PlatformEntry[K]){setDraft(row=>row?{...row,[key]:value}:row)}
  function accept(item:PlatformEntry,message:string){setItems(rows=>[...rows.filter(row=>row.id!==item.id),item].sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name)));select(item);setNotice(message)}
  const canLeave=()=>!dirty||window.confirm('Discard unsaved changes to this section?')
  async function save(event:FormEvent){event.preventDefault();if(!candidate)return;setBusy(true);setError('');setNotice('');try{const result=await request('/api/admin/platform-catalog'+(candidate.id?'/'+candidate.id:''),{method:candidate.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(candidate)});accept(result.item,result.item.status==='published'?'Section saved and published.':'Draft saved. It is not visible on the public website.')}catch(reason){setError(reason instanceof Error?reason.message:'Save failed.')}finally{setBusy(false)} }
  async function remove(){if(!draft?.id||!window.confirm('Delete '+draft.name+' and its uploaded media? This removes the section from the website.'))return;setBusy(true);setError('');try{await request('/api/admin/platform-catalog/'+draft.id,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:draft.version})});const remaining=items.filter(row=>row.id!==draft.id);setItems(remaining);if(remaining.length)select(remaining[0]);else{setDraft(null);setBaseline('')}setNotice('Section deleted.')}catch(reason){setError(reason instanceof Error?reason.message:'Delete failed.')}finally{setBusy(false)} }
  async function upload(kind:'photo'|'video'){if(!draft?.id)return;const file=kind==='photo'?photo:video;if(!file)return;setBusy(true);setError('');try{const data=new FormData();data.append('file',file);data.append('version',String(draft.version));const result=await request('/api/admin/platform-catalog/'+draft.id+'/'+kind,{method:'POST',body:data});accept(result.item,(kind==='photo'?'Photo':'Video')+' saved and selected as the default visual.')}catch(reason){setError(reason instanceof Error?reason.message:'Upload failed.')}finally{setBusy(false)} }
  async function removeMedia(kind:'photo'|'video'){if(!draft?.id||!window.confirm('Remove the uploaded '+kind+' for '+draft.name+'?'))return;setBusy(true);setError('');try{const result=await request('/api/admin/platform-catalog/'+draft.id+'/media/'+kind,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:draft.version})});accept(result.item,'Uploaded '+kind+' removed.')}catch(reason){setError(reason instanceof Error?reason.message:'Remove failed.')}finally{setBusy(false)} }
  function chooseFile(kind:'photo'|'video',file:File|null){if(!file)return;const types=kind==='photo'?['image/png','image/jpeg','image/webp']:['video/mp4','video/webm'];if(!types.includes(file.type)||!file.size||file.size>(kind==='photo'?10:100)*1024*1024){setError('Choose a supported '+kind+' within the '+(kind==='photo'?'10':'100')+' MB limit.');return}setError('');if(kind==='photo')setPhoto(file);else setVideo(file)}
  return <section className="admin-platforms"><div className="catalog-admin-heading"><div><h2>Platform sections</h2><p>Manage content and media for both platform groups.</p></div><button className="btn btn-primary btn-large" disabled={busy} onClick={()=>{if(canLeave()){const item=blank();item.order=Math.max(0,...items.filter(row=>row.group==='productivity').map(row=>row.order))+1;select(item);setBaseline('')}}}>Add section</button><button className="admin-secondary" disabled={!draft || loading} onClick={()=>{const target=document.getElementById('platform-media-upload');target?.scrollIntoView({behavior:'smooth',block:'start'});target?.focus({preventScroll:true})}}>Upload photo / video</button><button className="admin-secondary" disabled={busy} onClick={()=>{if(canLeave())void load()}}>Reload</button></div>
    {error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}
    {loading?<p role="status">Loading platform sections…</p>:<div className="catalog-admin-layout"><aside className="catalog-admin-list"><label className="field">Show group<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Both groups</option><option value="productivity">Productivity tools</option><option value="enterprise">Enterprise / Tvat AI</option></select></label>{items.filter(row=>filter==='all'||row.group===filter).map(row=><button key={row.id} disabled={busy} aria-pressed={draft?.id===row.id} onClick={()=>{if(canLeave())select(row)}}><strong>{row.name}</strong><small>{row.group==='enterprise'?'Tvat AI':'Productivity'} · {row.status} · Order {row.order}</small></button>)}{items.length===0&&<p>No sections yet. Add your first one.</p>}</aside>
      {draft&&candidate?<div className="catalog-admin-editor">        <div className="catalog-upload-heading" id="platform-media-upload" tabIndex={-1}><h3>Photos & videos</h3><p className="catalog-media-platform">{draft.name || 'New section'}</p><p>{!draft.id?'Save this new section to enable uploads.':dirty?'Save your text changes before uploading or removing media.':'Upload media for this section. A successful upload becomes its default visual.'}</p></div>
        <div className="catalog-upload-grid">{(['photo','video'] as const).map(kind=><div className="catalog-upload" key={kind}><h4>{kind==='photo'?'Photo':'Video'}</h4>{kind==='photo'?(photoPreview||draft.photo?<img src={photoPreview||draft.photo?.previewUrl} alt="Selected photo preview"/>:<div className="catalog-upload-placeholder">Add a product photo or screenshot</div>):(videoPreview||draft.video?<video controls preload="metadata" src={videoPreview||draft.video?.previewUrl} aria-label="Selected video preview"/>:<div className="catalog-upload-placeholder">Add a product walkthrough video</div>)}<input key={kind+uploadKey} aria-label={'Choose '+kind} type="file" accept={kind==='photo'?'image/png,image/jpeg,image/webp':'video/mp4,video/webm'} disabled={busy||dirty||!draft.id} onChange={e=>chooseFile(kind,e.target.files?.[0]||null)}/><p>{kind==='photo'?'PNG, JPG or WebP · up to 10 MB':'MP4 or WebM · up to 100 MB'}</p><button className="admin-secondary" disabled={busy||dirty||!draft.id||!(kind==='photo'?photo:video)} onClick={()=>upload(kind)}>{draft[kind]?'Replace':'Upload'} {kind}</button>{draft[kind]&&<button className="admin-secondary" disabled={busy||dirty} onClick={()=>removeMedia(kind)}>Remove {kind}</button>}</div>)}</div>
<form onSubmit={save}><fieldset disabled={busy}><legend>{draft.id?'Edit section':'New section'}</legend><div className="catalog-form-grid">
        <label className="field">Platform group<select value={draft.group} onChange={e=>change('group',e.target.value as PlatformEntry['group'])}><option value="productivity">Business Productivity & Efficiency Tools</option><option value="enterprise">Enterprise AI-native Platforms [Tvat AI]</option></select></label>
        <label className="field">Visibility<select value={draft.status} onChange={e=>change('status',e.target.value as PlatformEntry['status'])}><option value="draft">Draft — admin only</option><option value="published">Published — visible on website</option></select></label>
        <label className="field">Platform name<input required maxLength={120} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Category / subtitle<input required maxLength={180} value={draft.category} onChange={e=>change('category',e.target.value)}/></label>
        <label className="field catalog-wide">Headline<input maxLength={260} value={draft.headline} onChange={e=>change('headline',e.target.value)}/></label>
        <label className="field catalog-wide">Description<textarea required rows={5} maxLength={4000} value={draft.description} onChange={e=>change('description',e.target.value)}/></label>
        <label className="field">Features — one per line<textarea rows={6} value={features} onChange={e=>setFeatures(e.target.value)}/><small>Up to 16 features, 350 characters each.</small></label><label className="field">Illustration workflow — one step per line<textarea rows={6} value={flow} onChange={e=>setFlow(e.target.value)}/><small>Up to 6 short steps for productivity illustrations.</small></label>
        <label className="field catalog-wide">Outcome / closing statement<input maxLength={600} value={draft.outcome} onChange={e=>change('outcome',e.target.value)}/></label>
        <label className="field">Display order<input type="number" min={0} max={10000} step={1} required value={draft.order} onChange={e=>change('order',Number(e.target.value))}/><small>Lower numbers appear first within the group.</small></label><label className="field">Theme accent<select value={draft.color} onChange={e=>change('color',e.target.value)}><option value="royal">Royal blue</option><option value="turquoise">Turquoise</option><option value="sky">Sky blue</option><option value="violet">Violet</option></select></label>
        <label className="field">Default visual<select value={draft.mediaMode} onChange={e=>change('mediaMode',e.target.value as PlatformEntry['mediaMode'])}><option value="illustration">Original illustration / placeholder</option><option value="photo" disabled={!draft.photo&&!draft.image}>Photo</option><option value="video" disabled={!draft.video}>Video</option></select></label><label className="field">Photo description (alt text)<input maxLength={250} value={draft.imageAlt} onChange={e=>change('imageAlt',e.target.value)}/></label>
        <label className="field catalog-wide">Video transcript<textarea rows={4} maxLength={6000} value={draft.transcript} onChange={e=>change('transcript',e.target.value)}/></label>
      </div><div className="button-row"><button className="btn btn-primary btn-large" disabled={busy}>{busy?'Saving…':draft.status==='published'?'Save & publish':'Save draft'}</button>{draft.id&&<button type="button" className="admin-secondary" onClick={remove}>Delete section</button>}{draft.id&&<a href={'/#'+draft.anchor} target="_blank" rel="noreferrer">View website ↗</a>}</div></fieldset></form>
        <h3 className="catalog-preview-title">Visual preview</h3><div className={'catalog-admin-preview accent-'+draft.color}><PlatformVisual item={candidate} admin /></div>
      </div>:<p>Select a section or choose Add section to begin.</p>}
    </div>}
  </section>
}