import { useEffect,useState } from 'react'
import type { FormEvent } from 'react'
export type CmsRequest=(url:string,options?:RequestInit)=>Promise<any>
export const socialNames:Record<string,string>={x:'X (Twitter)',facebook:'Facebook',instagram:'Instagram'}
type Account={accountId:string;label:string;configured:boolean;verifiedAt:string;token:string;clearToken:boolean}
type Settings={version:number;siteUrl:string;graphVersion:string;accounts:Record<string,Account>}
export default function SocialAccounts({request}:{request:CmsRequest}){
 const [settings,setSettings]=useState<Settings|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 function hydrate(result:Settings){setSettings({...result,accounts:Object.fromEntries(Object.entries(result.accounts).map(([key,account])=>[key,{...account,token:'',clearToken:false}]))})}
 useEffect(()=>{request('/api/admin/social-settings').then(hydrate).catch(e=>setError(e.message))},[])
 function account(platform:string,key:string,value:unknown){setSettings(old=>old?{...old,accounts:{...old.accounts,[platform]:{...old.accounts[platform],[key]:value}}}:old);setNotice('')}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{hydrate(await request('/api/admin/social-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)}));setNotice('Settings saved. Verify each account before publishing.')}catch(e){setError(e instanceof Error?e.message:'Unable to save settings.')}finally{setBusy(false)}}
 async function verify(platform:string){setBusy(true);setError('');setNotice('');try{hydrate(await request('/api/admin/social-settings/'+platform+'/verify',{method:'POST'}));setNotice(socialNames[platform]+' account verified. Publishing permission is checked by the platform when posting.')}catch(e){setError(e instanceof Error?e.message:'Unable to verify account.')}finally{setBusy(false)}}
 return <div className="social-settings"><h2>Company social accounts</h2><p>Connect official company accounts using their platform access tokens. Tokens stay on the server and are not returned to the browser after saving.</p>
 {error&&<p role="alert" className="admin-error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}
 <details className="cms-setup" open><summary>Setup instructions</summary><ol><li><strong>Website:</strong> deploy the website on a public HTTPS domain and enter it below. Social links open the complete insight.</li><li><strong>X:</strong> create a developer app with posting access. Obtain an OAuth user access token with tweet.read, tweet.write and users.read scopes. An app-only bearer token cannot publish for your account. API access must be enabled for your app.</li><li><strong>Facebook:</strong> create a Meta app and configure a company Page. Obtain a Page access token with pages_manage_posts and pages_read_engagement permissions. Enter the numeric Page ID.</li><li><strong>Instagram:</strong> use a Business or Creator account linked to the Facebook Page. Configure Instagram API with Facebook Login, including instagram_basic, instagram_content_publish and the required Page permissions. Enter the Instagram professional account ID and its authorized token.</li><li>Save, verify the account identity, then use an insight’s social preview to publish. Replace expired tokens here. Check the platform’s current app review and access requirements.</li></ol><p><a href="https://docs.x.com/x-api/posts/manage-tweets/quickstart" target="_blank" rel="noreferrer">X setup</a> · <a href="https://developers.facebook.com/docs/pages-api/posts/" target="_blank" rel="noreferrer">Facebook publishing</a> · <a href="https://developers.facebook.com/docs/instagram-platform/instagram-api-with-facebook-login/content-publishing/" target="_blank" rel="noreferrer">Instagram publishing</a></p></details>
 {settings?<form onSubmit={save}><fieldset disabled={busy}><legend className="sr-only">Social configuration</legend><div className="cms-grid"><label className="field">Public website URL<input type="url" placeholder="https://www.i-genext.com" value={settings.siteUrl} onChange={e=>setSettings({...settings,siteUrl:e.target.value})}/></label><label className="field">Meta Graph API version<input required pattern="v[0-9]{2}\.0" value={settings.graphVersion} onChange={e=>setSettings({...settings,graphVersion:e.target.value})}/></label></div>
 <div className="social-account-grid">{Object.entries(socialNames).map(([platform,label])=><section className="social-account" key={platform}><h3>{label}</h3><p className="label">{settings.accounts[platform].verifiedAt?'Identity verified':settings.accounts[platform].configured?'Token saved · Verify account':'Not configured'}</p><label className="field">Account label<input maxLength={100} value={settings.accounts[platform].label} onChange={e=>account(platform,'label',e.target.value)}/></label><label className="field">{platform==='x'?'User ID (optional until verified)':platform==='facebook'?'Facebook Page ID':'Instagram account ID'}<input inputMode="numeric" pattern="[0-9]*" maxLength={40} value={settings.accounts[platform].accountId} onChange={e=>account(platform,'accountId',e.target.value)}/></label><label className="field">Access token<input type="password" autoComplete="new-password" maxLength={8192} value={settings.accounts[platform].token} placeholder={settings.accounts[platform].configured?'Saved securely; leave blank to keep':'Paste authorized account token'} onChange={e=>account(platform,'token',e.target.value)}/></label><label className="social-check"><input type="checkbox" checked={settings.accounts[platform].clearToken} onChange={e=>account(platform,'clearToken',e.target.checked)}/>Disconnect this account when saved</label><button type="button" className="admin-secondary" disabled={!settings.accounts[platform].configured} onClick={()=>verify(platform)}>Verify {label}</button></section>)}</div>
 <button className="btn btn-primary btn-large">{busy?'Working…':'Save social settings'}</button></fieldset></form>:<p role="status">Loading account settings…</p>}
 </div>
}
