import test from 'node:test'
import assert from 'node:assert/strict'
import express from 'express'
import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import { createPlatformCatalog, registerPlatformCatalog } from '../src/platform-catalog.js'
import { createAdminAuth, hashPassword } from '../src/admin.js'
const entry = (extra={}) => ({ name:'Test platform',category:'Test category',headline:'A useful headline',description:'A complete platform description.',features:['One feature'],flow:['Plan','Deliver'],outcome:'Useful outcome',group:'productivity',status:'draft',mediaMode:'illustration',color:'royal',order:1,imageAlt:'Product screen',transcript:'',...extra })
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j5WQAAAAASUVORK5CYII=','base64')
const webm=Buffer.concat([Buffer.from([26,69,223,163]),Buffer.from('webm'),Buffer.alloc(32)])
function form(bytes,mime,version){const data=new FormData();data.append('file',new Blob([bytes],{type:mime}),'upload');data.append('version',String(version));return data}
async function fixture(t){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'igenext-catalog-'));const credentialsFile=path.join(directory,'credentials.json');await fs.writeFile(credentialsFile,JSON.stringify({username:'tester',...await hashPassword('test-only-password')}));const store=createPlatformCatalog({directory:path.join(directory,'catalog'),databaseUrl:'',nodeEnv:'test',seed:[]});await store.ready;const app=express();app.use(express.json());const auth=createAdminAuth({credentialsFile});app.post('/api/admin/login',auth.login);registerPlatformCatalog(app,{store,auth,origin:'http://localhost:5173',photoLimit:1024,videoLimit:1024});const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s))});const base='http://127.0.0.1:'+server.address().port;t.after(async()=>{await new Promise(resolve=>server.close(resolve));await store.close();assert.equal(path.dirname(directory),path.resolve(os.tmpdir()));await fs.rm(directory,{recursive:true,force:true})});const login=await fetch(base+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'tester',password:'test-only-password'})});const headers={Cookie:login.headers.get('set-cookie').split(';')[0],Origin:'http://localhost:5173'};const json=(method,body)=>({method,headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});return {directory,store,base,headers,json}}
test('catalog protects administration and rejects malformed content',async t=>{const {base,headers,json}=await fixture(t);assert.equal((await fetch(base+'/api/admin/platform-catalog')).status,401);assert.equal((await fetch(base+'/api/admin/platform-catalog',{...json('POST',entry()),headers:{...headers,Origin:'https://foreign.invalid','Content-Type':'application/json'}})).status,403);for(const body of [entry({name:''}),entry({order:-1}),entry({features:['x'.repeat(351)]}),entry({group:'unknown'}),entry({mediaMode:'video'})])assert.equal((await fetch(base+'/api/admin/platform-catalog',json('POST',body))).status,400)})
test('create, publish, edit, reorder, move group and delete persist without reseeding',async t=>{const {base,json,store,directory}=await fixture(t);let response=await fetch(base+'/api/admin/platform-catalog',json('POST',entry()));assert.equal(response.status,201);let row=(await response.json()).item;assert.equal((await (await fetch(base+'/api/platform-catalog')).json()).items.length,0);response=await fetch(base+'/api/admin/platform-catalog/'+row.id,json('PUT',{...row,status:'published'}));row=(await response.json()).item;assert.equal((await store.list())[0].name,'Test platform');const second=await store.create(entry({name:'First in list',status:'published',order:0}));assert.equal((await store.list())[0].id,second.id);const stale=row;row=(await (await fetch(base+'/api/admin/platform-catalog/'+row.id,json('PUT',{...row,name:'Renamed',group:'enterprise',order:0}))).json()).item;assert.equal(row.group,'enterprise');assert.equal((await fetch(base+'/api/admin/platform-catalog/'+row.id,json('PUT',stale))).status,409);assert.equal((await fetch(base+'/api/admin/platform-catalog/'+row.id,json('DELETE',{version:stale.version}))).status,409);assert.equal((await fetch(base+'/api/admin/platform-catalog/'+row.id,json('DELETE',{version:row.version}))).status,200);const reopened=createPlatformCatalog({directory:path.join(directory,'catalog'),databaseUrl:'',nodeEnv:'test',seed:[{...entry(),id:'should-not-reseed'}]});await reopened.ready;assert.deepEqual((await reopened.list()).map(x=>x.id),[second.id]);await reopened.close()})
test('draft media is private; publishing enables photo and range-served video, with default selection',async t=>{const {base,headers,json,store}=await fixture(t);let row=await store.create(entry());let response=await fetch(base+'/api/admin/platform-catalog/'+row.id+'/photo',{method:'POST',headers,body:form(png,'image/png',row.version)});assert.equal(response.status,201);row=(await response.json()).item;assert.equal(row.mediaMode,'photo');assert.equal((await fetch(base+row.photo.url)).status,404);assert.equal((await fetch(base+row.photo.previewUrl,{headers})).status,200);assert.equal((await fetch(base+row.photo.previewUrl)).status,401);response=await fetch(base+'/api/admin/platform-catalog/'+row.id+'/video',{method:'POST',headers,body:form(webm,'video/webm',row.version)});assert.equal(response.status,201);row=(await response.json()).item;assert.equal(row.mediaMode,'video');row=(await (await fetch(base+'/api/admin/platform-catalog/'+row.id,json('PUT',{...row,status:'published'}))).json()).item;const range=await fetch(base+row.video.url,{headers:{Range:'bytes=0-7'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,8);assert.equal((await fetch(base+row.photo.url)).headers.get('content-type'),'image/png');const publicItem=(await (await fetch(base+'/api/platform-catalog')).json()).items[0];assert.equal(publicItem.video.previewUrl,undefined);assert.equal(publicItem.video.filename,undefined);row=(await (await fetch(base+'/api/admin/platform-catalog/'+row.id+'/media/video',json('DELETE',{version:row.version}))).json()).item;assert.equal(row.video,null);assert.equal(row.mediaMode,'illustration');assert.ok(row.photo)})
test('media validation and optimistic conflicts preserve existing files; replacement and section deletion clean up',async t=>{const {base,headers,json,store}=await fixture(t);let row=await store.create(entry({status:'published'}));row=(await (await fetch(base+'/api/admin/platform-catalog/'+row.id+'/photo',{method:'POST',headers,body:form(png,'image/png',row.version)})).json()).item;const old=row.photo.url;for(const [bytes,mime,version,status]of[[Buffer.from('<svg/>'),'image/svg+xml',row.version,400],[Buffer.from('not a png'),'image/png',row.version,400],[Buffer.alloc(2048),'image/png',row.version,413],[png,'image/png',1,409]]){assert.equal((await fetch(base+'/api/admin/platform-catalog/'+row.id+'/photo',{method:'POST',headers,body:form(bytes,mime,version)})).status,status);assert.equal((await store.list())[0].photo.url,old)}assert.equal((await fs.readdir(store.root)).filter(x=>x.endsWith('.png')).length,1);row=(await (await fetch(base+'/api/admin/platform-catalog/'+row.id+'/photo',{method:'POST',headers,body:form(png,'image/png',row.version)})).json()).item;assert.notEqual(row.photo.url,old);assert.equal((await fetch(base+old)).status,404);assert.equal((await fs.readdir(store.root)).filter(x=>x.endsWith('.png')).length,1);assert.equal((await fetch(base+'/api/admin/platform-catalog/'+row.id,json('DELETE',{version:row.version}))).status,200);assert.equal((await fs.readdir(store.root)).filter(x=>x.endsWith('.png')).length,0);assert.equal((await fetch(base+row.photo.url)).status,404)})
test('seed migration copies legacy video once and preserves subsequent admin changes',async t=>{const {directory}=await fixture(t);const legacyRoot=path.join(directory,'legacy');await fs.mkdir(legacyRoot);const filename=randomUUID()+'.webm';await fs.writeFile(path.join(legacyRoot,filename),webm);const legacyStore={root:legacyRoot,get:async()=>({filename,mime:'video/webm',size:webm.length,transcript:'Legacy transcript'})};const target=path.join(directory,'migrated');const seed=[{...entry({status:'published'}),id:'envision',anchor:'tool-envision',version:1}];const migrated=createPlatformCatalog({directory:target,databaseUrl:'',nodeEnv:'test',seed,legacyStore});await migrated.ready;let row=(await migrated.list(true))[0];assert.equal(row.transcript,'Legacy transcript');assert.ok(row.video);row=await migrated.update(row.id,{...row,name:'Edited after migration'});await migrated.close();const reopened=createPlatformCatalog({directory:target,databaseUrl:'',nodeEnv:'test',seed,legacyStore});await reopened.ready;assert.equal((await reopened.list())[0].name,'Edited after migration');await reopened.close()})