import { pathToFileURL } from 'node:url'
import { mkdir, readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
const moduleName = process.env.PLAYWRIGHT_MODULE
const { chromium } = await import(moduleName ? pathToFileURL(moduleName).href : 'playwright')
const browser = await chromium.launch({headless:true})
const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'})
const errors=[]
page.on('pageerror',e=>errors.push(e.message))
const base = process.env.TEST_BASE_URL || 'http://localhost:5173'
await mkdir('test-results',{recursive:true})
try {
  await page.goto(base)
  console.log('Loaded', await page.title()); await page.screenshot({path:'test-results/initial.png'}); console.log('Headings', await page.locator('h1').allTextContents()); console.log('Runtime errors', errors); await page.getByRole('heading',{name:/Your next chapter/}).waitFor()
  await page.screenshot({path:'test-results/desktop-home.png'})
  await page.getByRole('button',{name:'Search the site'}).click()
  await page.getByPlaceholder('Try AI, finance or manufacturing').fill('manufacturing')
  await page.getByRole('link',{name:/Industry Manufacturing/}).click()
  await page.getByRole('heading',{name:'Connect factory decisions to business performance.'}).waitFor()
  await page.locator('#industries').getByRole('button',{name:/Financial Services/}).click()
  await page.getByRole('heading',{name:'Move faster with trust built into the workflow.'}).waitFor()
  await page.locator('#capability-ai summary').click()
  assert.equal(await page.locator('#capability-ai').getAttribute('open'),'')
  await page.locator('#readiness').scrollIntoViewIfNeeded()
  assert.equal(await page.getByRole('button',{name:'Continue →',exact:true}).isDisabled(),true)
  for(let i=0;i<5;i++) {
    await page.locator('#readiness input[type=radio]').nth(i === 4 ? 0 : 2).check()
    await page.getByRole('button',{name:i===4?'See my roadmap →':'Continue →',exact:true}).click()
  }
  await page.getByRole('heading',{name:'Prepare to scale',exact:true}).waitFor()
  const download = page.waitForEvent('download')
  await page.getByRole('button',{name:'Download roadmap ↓',exact:true}).click()
  assert.equal((await download).suggestedFilename(),'igenext-ai-readiness.txt')
  await page.getByRole('button',{name:'Discuss my roadmap ↗'}).click()
  assert.equal(await page.locator('select[name=area]').inputValue(),'AI, Data & Automation')
  assert.match(await page.locator('textarea[name=message]').inputValue(),/53\/100/)
  const inputs=page.locator('#value-calculator input')
  await inputs.nth(3).fill('0')
  await page.getByText('Not reached',{exact:true}).waitFor()
  await inputs.nth(3).fill('75')
  await inputs.nth(0).fill('-1')
  await page.locator('#value-calculator [role=alert]').waitFor()
  await inputs.nth(0).fill('400')
  await page.locator('#insights').getByRole('button',{name:'Finance',exact:true}).click()
  assert.equal(await page.locator('#insights .insight-card').count(),1)
  await page.getByRole('button',{name:'Save Design finance for decision speed',exact:true}).click()
  await page.reload()
  await page.locator('#insights').getByRole('button',{name:'My reading list (1)'}).click()
  assert.equal(await page.locator('#insights .insight-card').count(),1)
  await page.getByRole('link',{name:'Read perspective ↗',exact:true}).click()
  await page.getByRole('dialog').waitFor()
  assert.ok(await page.getByRole('heading',{name:'Work backwards from the decision'}).isVisible())
  await page.keyboard.press('Escape')
  await page.getByRole('dialog').waitFor({state:'hidden'})
  await page.goto(base+'/#insight/ai-pilot-to-operating-model')
  await page.getByRole('dialog').waitFor()
  await page.getByRole('button',{name:'Close dialog'}).click()
  await page.getByRole('button',{name:'Export CSV'}).scrollIntoViewIfNeeded()
  const csv=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export CSV'}).click()
  const csvDownload=await csv
  const csvBody=await readFile(await csvDownload.path(),'utf8')
  assert.match(csvBody,/"Open obligations","126"/)
  await page.locator('#contact-name').fill('Browser Verification')
  await page.locator('input[name=email]').fill('browser-test@example.com')
  await page.locator('input[name=company]').fill('Verification Only')
  await page.locator('input[name=designation]').fill('Director')
  await page.locator('input[name=phone]').fill('+91 98765 43210')
  await page.locator('select[name=area]').selectOption('AI, Data & Automation')
  await page.locator('textarea[name=message]').fill('Automated browser verification. This is a local test enquiry.')
  await page.locator('input[name=consent]').check()
  await page.route('**/api/contact',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,message:'Service temporarily unavailable.'})}))
  await page.getByRole('button',{name:'Start a conversation ↗',exact:true}).click()
  await page.getByRole('alert').filter({hasText:'Service temporarily unavailable.'}).waitFor()
  assert.equal(await page.locator('#contact-name').inputValue(),'Browser Verification')
  await page.unroute('**/api/contact')
  await page.route('**/api/contact',route=>route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,reference:'IG-browser-preview'})}))
  await page.getByRole('button',{name:'Start a conversation ↗',exact:true}).click()
  await page.getByRole('status').filter({hasText:'Your enquiry has been saved.'}).waitFor()
  await page.locator('#readiness').screenshot({path:'test-results/readiness.png'})
  for(const width of [390,768,1024,1440]) {
    await page.setViewportSize({width,height:900})
    await page.goto(base)
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth), 'Overflow at '+width)
    if(width===390) { const box = await page.locator('.hero-copy').boundingBox(); assert.ok(box.x >= 12 && box.width >= width - 40, 'Mobile hero must use the available width');
      await page.getByRole('button',{name:'Toggle navigation'}).click()
      await page.locator('#primary-nav').getByRole('link',{name:'Insights',exact:true}).click()
      assert.equal(await page.getByRole('button',{name:'Toggle navigation'}).getAttribute('aria-expanded'),'false')
      await page.goto(base)
      await page.screenshot({path:'test-results/mobile-home.png'})
    }
  }
  assert.deepEqual(errors,[])

  assert.equal(await page.locator('.capability-list details').count(),8)
  assert.equal(await page.locator('.platform-card').count(),6)
  assert.equal(await page.locator('.leadership-grid article').count(),4)
  assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(0, 0, 0)')
  await page.locator('#capability-finance-advisory summary').click()
  await page.getByText('Managed payroll services',{exact:true}).waitFor()
  await page.locator('#capability-forensic summary').click()
  await page.getByText('Digital forensics',{exact:true}).waitFor()
  await page.locator('#platform-0 button').click()
  assert.equal(await page.locator('select[name=area]').inputValue(),'Tech Solutions')
  assert.match(await page.locator('textarea[name=message]').inputValue(),/Plinari/)
  await page.locator('#locations').getByRole('button',{name:'Mumbai office on map',exact:true}).click()
  assert.match(await page.locator('.office-balloon address').textContent(),/Enam Sambhav/)
  assert.match(await page.locator('.office-balloon a').getAttribute('href'),/Mumbai/)
  await page.locator('#group').screenshot({path:'test-results/deck-group.png'})
  await page.locator('#leadership').scrollIntoViewIfNeeded()
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('.leader-portrait img')).every(img=>img.complete && img.naturalWidth>0))
  await page.locator('#leadership').screenshot({path:'test-results/deck-leadership.png'})
  await page.locator('#platforms').screenshot({path:'test-results/deck-platforms.png'})
  await page.locator('#readiness').screenshot({path:'test-results/deck-assessment.png'})
  await page.locator('#contact').screenshot({path:'test-results/deck-contact.png'})
  await page.goto(base)
  await page.screenshot({path:'test-results/deck-desktop.png'})
  await page.setViewportSize({width:390,height:900})
  await page.screenshot({path:'test-results/deck-mobile.png'})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  console.log('Deck checks passed: black base, 8 services, 6 platforms, 4 leaders, office selection and platform enquiry context.')
  console.log('Browser checks passed: desktop/mobile, search, industry selection, service expansion, assessment, downloads, calculator, saved/deep-linked insights, enquiry failure recovery and success UI; no runtime errors. Contact persistence and email are verified separately with isolated data.')
} finally { await browser.close() }
